server:
  port: 9201

spring:
  cloud:
    gateway:
      routes: #配置路由路径
        - id: api-route
          uri: lb://ypier-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1

        - id: ypier-auth
          uri: lb://ypier-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址
  # redis 配置
  redis:
    database: 0
    host: 172.30.3.212
    port: 7006

secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"
      - "/auth/rsa/publicKey"
      - "/system/user/login"


# 暴露 admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
